apiVersion: 1

datasources:
  - name: 'Timely'
    type: 'nsa-timely-datasource'
    access: proxy
    isDefault: true
    orgId: 1
    version: 1
    editable: true
    jsonData:
      path: '/resources'
    secureJsonData:
      apiKey: 'api-key'
